baseURL = "https://denv.it/blog/"
languageCode = "en-us"
title = "Denys Vitali's Blog"
theme = "minimal-tbmfw"

[params]
site_author = "Denys Vitali"
site_description = "Tech tales"
location = "Lugano, Switzerland"

piwik_enabled = true
piwik_host = "matomo.ded1.denv.it"
piwik_site_id = 4

disqusShortname = "denvit"
main_website = "https://denv.it/"
